### ISSUE TITLE
Help to translate terminal-quest to Portuguese

### ISSUE THREAD

**Issue by carloseduleal** [KanoComputing/terminal-quest#101]
Hey, everyone!

Sorry to raise an issue about it, but we tried to send e-mail to caroline@kano.me, but it seems like the e-mail doesn't exist anymore. 
We would like to run some sessions using Kanux to some special kids at Brazil. So we would like to translate the terminal-quest to Portuguese.

We are trying to run the cloned terminal-quest inside Kanux, but we're facing an issue (it seems like GTK version conflict, but we couldn't solve it):

```
Carlos@kano ~/terminal-quest/bin $ ./linux-story-gui
Traceback (most recent call last):
  File "./linux-story-gui", line 99, in <module>
    main(challenge, step, debug)
  File "./linux-story-gui", line 55, in main
    window = MainWindow(challenge, step, debug)
  File "/home/Carlos/terminal-quest/linux_story/gtk3/MainWindow.py",
line 44, in __init__
    apply_styling_to_screen(self.CSS_FILE)
  File "/usr/lib/python2.7/dist-packages/kano/gtk3/apply_styles.py",
line 39, in apply_styling_to_screen
    css.load_from_path(css_file)
GLib.Error: gtk-css-provider-error-quark: style.css:195:13Missing name
of pseudo-class (1)
```

**Kanux version**: Kanux-Beta-v3.15.0-Lovelace-jessie-rc-2018-04-03_09-51.img
**HW**: Raspberry PI 3

Any idea how to execute the project skipping this issue? We saw the Italian version and the steps to translate, it seems clear, but this issue is blocking us.

PS: This issue only happens when we try to clone the terminal-quest project, build it and execute ./terminal-quest-gui. Using the built-in terminal quest version it is working fine (the same to italian version).

**Comment by carloseduleal** [comment]
Thanks for the reply, @Ealdwulf!

Thanks for the explanation about the i18n, got it!

Well, is was looking the images available: http://dev.kano.me/public/ all the images related to jessie are the same that we are using: Kanux-Beta-v3.15.0-Lovelace-jessie-rc-2018-04-03_09-51.img

Do you have another link to download that one mentioned by you?

**Comment by carloseduleal** [comment]
Hey, @Ealdwulf, I'm closing this thread, it is working using the Kanux Beta 4.0.0 version. I'm also able to generate the pt_BR.po with the messages to be translated. Thank you for the support!
